url: "https://v2.launchedfm.com"
paginate: 20
paginate_path: "/page:num/"

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /episodes/:title
  - scope:
      path: "pages"
    values:
      permalink: /:basename:output_ext
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag