url: "https://v2.launchedfm.com"
paginate: 20
paginate_path: "/:num/"

title: "Launched FM"
description: "The stories behind your favorite apps."

logo: /assets/images/launched_artwork-1024.jpg

twitter:
  username: LaunchedFM
  card: summary

social:
  name: Launched FM
  links:
    - https://twitter.com/LaunchedFM

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /episodes/:title
  - scope:
      path: "pages"
    values:
      permalink: /:basename:output_ext
  - scope:
      path: ""
    values:
      layout: "default"
      image: /assets/images/launched_artwork-1024.jpg

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag